/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITheAssetsClub,
  ITheAssetsClubInterface,
} from "../../contracts/ITheAssetsClub";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "count",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class ITheAssetsClub__factory {
  static readonly abi = _abi;
  static createInterface(): ITheAssetsClubInterface {
    return new utils.Interface(_abi) as ITheAssetsClubInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITheAssetsClub {
    return new Contract(address, _abi, signerOrProvider) as ITheAssetsClub;
  }
}
