/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SimpleWhitelist,
  SimpleWhitelistInterface,
} from "../../contracts/SimpleWhitelist";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class SimpleWhitelist__factory {
  static readonly abi = _abi;
  static createInterface(): SimpleWhitelistInterface {
    return new utils.Interface(_abi) as SimpleWhitelistInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SimpleWhitelist {
    return new Contract(address, _abi, signerOrProvider) as SimpleWhitelist;
  }
}
