/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TheAssetsClubOZ } from "./TheAssetsClubOZ";
export type { TheAssetsClubOZEnumerable } from "./TheAssetsClubOZEnumerable";
