/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TheAssetsClubA } from "./TheAssetsClubA";
export type { TheAssetsClubOZ } from "./TheAssetsClubOZ";
export type { TheAssetsClubPsi } from "./TheAssetsClubPsi";
